# Generated by Django 4.2.1 on 2023-08-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamePlaytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_hours', models.IntegerField(default=0, verbose_name='Horas jugadas')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.user')),
            ],
            options={
                'verbose_name': 'Tiempo de juego por usuario',
                'verbose_name_plural': 'Tiempos de juego por usuarios',
            },
        ),
    ]
