# Generated by Django 4.2.1 on 2023-09-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_usergameplaytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funny', models.CharField(max_length=200, null=True, verbose_name='Divertido')),
                ('posted', models.DateField(null=True, verbose_name='Posteado')),
                ('last_edited', models.CharField(max_length=200, null=True, verbose_name='Ultima vez editado')),
                ('helpful', models.CharField(max_length=200, null=True, verbose_name='Fue de ayuda?')),
                ('recommend', models.BooleanField(null=True, verbose_name='Recomendado?')),
                ('review', models.TextField(verbose_name='Reseña')),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Juego de la reseña')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.user', verbose_name='Usuario de la reseña')),
            ],
            options={
                'verbose_name': 'Reseña de usuario',
                'verbose_name_plural': 'Reseñas de usuarios',
            },
        ),
    ]
