# Generated by Django 4.2.1 on 2023-09-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_userreviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
