# Generated by Django 4.2.1 on 2023-09-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_game_id_userreviews_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviews',
            name='review',
            field=models.TextField(null=True, verbose_name='Reseña'),
        ),
    ]
